# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- task: VSBuild@1
  inputs:
    solution: '**\Tdp.GeospatialConverter.Svc.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:PublishProfile=CI'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\Build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Build'
    CleanTargetFolder: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Build'
    ArtifactName: 'drop'
    publishLocation: 'Container'